version: '3'
services:
  db:
    image: mysql:debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Farmacia
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

