--Pruebas de replicacion (CRUD en distintos nodos del cluster)
SELECT * from usuarios;
-- Insertamos datos
--INSERT INTO usuarios (id, nombre, apellido, edad) VALUES (uuid(), 'Juan', 'Perez', 30);
--INSERT INTO usuarios (id, nombre, apellido, edad) VALUES (uuid(), 'Maria', 'Lopez', 25);
-- Actualizamos
-- UPDATE usuarios SET nombre = 'Pedro' WHERE id = <id_del_usuario>;
-- Borramos
-- DELETE FROM usuarios WHERE id = <id_del_usuario>;
